name: Core Benchmarks

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, labeled ]
    branches:
      - master
  workflow_dispatch:

jobs:
  synthesis:
    strategy:
      matrix:
        config: [basic, full]
    name: Run synthesis benchmarks
    if: github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'benchmark') 
    runs-on: ubuntu-latest
    timeout-minutes: 40
    container: ghcr.io/kuznia-rdzeni/amaranth-synth:ecp5-2023.11.19_v
    steps:
      - uses: actions/checkout@v4

      - name: Set ownership (Github Actions workaround)
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Synthesize
        run: |
          . venv/bin/activate
          PYTHONHASHSEED=0 ./scripts/synthesize.py --verbose --strip-debug --config ${{ matrix.config }}

      - name: Print synthesis information
        run: cat ./build/top.tim

      - name: Collect Benchmark information
        run: |
          . venv/bin/activate
          ./scripts/parse_benchmark_info.py -o synth-benchmark-${{ matrix.config }}.json
          cat ./synth-benchmark-${{ matrix.config }}.json

      - uses: actions/upload-artifact@v4
        with:
          name: synth_benchmark_results-${{ matrix.config }}
          path: synth-benchmark-${{ matrix.config }}.json


  build-perf-benchmarks:
    name: Build performance benchmarks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'benchmark')
    container: ghcr.io/kuznia-rdzeni/riscv-toolchain:2024.03.12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build embench
        run: cd test/external/embench && make

      - uses: actions/upload-artifact@v4
        with:
          name: "embench"
          path: |
            test/external/embench/build

  run-perf-benchmarks:
    name: Run performance benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: ghcr.io/kuznia-rdzeni/verilator:v5.008-2023.11.19_v
    needs: build-perf-benchmarks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ownership (Github Actions workaround)
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Generate Verilog
        run: |
          . venv/bin/activate
          PYTHONHASHSEED=0 TRANSACTRON_VERBOSE=1 ./scripts/gen_verilog.py --verbose --config full

      - uses: actions/download-artifact@v4
        with:
          name: "embench"
          path: test/external/embench/build

      - name: Run benchmarks
        run: |
          . venv/bin/activate
          scripts/run_benchmarks.py -o perf_benchmark.json --summary perf.md
          cat perf.md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: perf_benchmark_results
          path: perf_benchmark.json
